####LOAD THE DPLYR PACKAGE
require(dplyr)

##LOAD THE DATASET

store <- read.csv("FINAL DEPARTMENTAL STORE.csv")

### : DATA TRANSFORMATION

###i.GET THE INFORMATION OF THE COLUMNS 4-10
###ii.WHERE PRODUCT_CATEGORY IS 'household'
###iii.ARRANGED IN ASCENDING ORDER OF QUANTITY_DEMANDED. 

store1 <- select(store, 4:10)
store2 <- filter(store1, PRODUCT_TYPE=='household')
store3<-arrange(store2, QUANTITY_DEMANDED)
View(store3)

### : STATISTICAL INTERPRETATION

###i. FIND THE AVERAGE AND SUMMATION OF QUANTITY_DEMANDED
###ii. GROUPED BY PRODUCT CATEGORY

store4 <- group_by(store3, PRODUCT_CATEGORY)
summarise(store3, AVERAGE=mean(QUANTITY_DEMANDED),SUM=sum(QUANTITY_DEMANDED))

